In [17]:
import numpy as np
import pandas as pd

In [35]:
#create an empty array
empty_array= np.empty([2,2], int)
empty_array.shape
# empty_array.size
# empty_array

(2, 2)

In [37]:
a=np.array([])
b=np.array([1,2])



In [41]:
#check whether the array is empty
def check_empty(a):
    if a.size == 0:
        print(a, ' : Empty')
    else:
        print(b, ' : Non Empty')

In [43]:
check_empty(b)

[1 2]  : Non Empty


In [45]:
def get_elements(c_array):
    return c_array.ndim and c_array.size




In [50]:

print(a, "element_count: ",get_elements(a))
print(a, "element_count: ",get_elements(b))

[] element_count:  0
[] element_count:  2


In [57]:
a = np.arange(12,30,3)
d=a.reshape(2,3)
print(a,'. shape', a.shape)
print("reshaping.....")
print('reshaped', d)


[12 15 18 21 24 27] . shape (6,)
reshaping.....
reshaped [[12 15 18]
 [21 24 27]]


In [63]:
q=np.random.randint(10,size=5)
j=np.random.randint(9,size=(2,3))
j

array([[1, 6, 6],
       [7, 4, 5]])

In [66]:
strings=np.array(["here","kalu","love"],dtype=str)
strings

array(['here', 'kalu', 'love'], dtype='<U4')